### ISSUE TITLE
raise NotImplementedError NotImplementedError

### ISSUE THREAD

**Issue by CHonChou** [cwq159/PyTorch-Spiking-YOLOv3#1]
when i tried to transform ann to snn,and run the command "python3 ann_to_snn.py --model_def config/spiking-yolov3-tin
y.cfg",it raise the error"raise NotImplementedError NotImplementedError"

File "/home/kugatsu/my_py_project/bindsnet/PyTorch-Spiking-YOLOv3-main/ann_to_snn.py", line 99, in <module>
    batch_size=8,
  File "/home/kugatsu/my_py_project/bindsnet/PyTorch-Spiking-YOLOv3-main/snn_test.py", line 40, in ann_evaluate
    output1, output2 = partial_ann(imgs)  # two branches
  File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kugatsu/my_py_project/bindsnet/PyTorch-Spiking-YOLOv3-main/ann_to_snn.py", line 26, in forward
    x = self.list[i](x)
  File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 223, in _forward_unimplemented
    raise NotImplementedError
NotImplementedError

**Comment by cwq159** [comment]
u need to train the model first，and add "weights_path" in the command line.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上7:40
收件人:&nbsp;"cwq159/PyTorch-Spiking-YOLOv3"<PyTorch-Spiking-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cwq159/PyTorch-Spiking-YOLOv3] raise NotImplementedError NotImplementedError (#1)





 
when i tried to transform ann to snn,and run the command "python3 ann_to_snn.py --model_def config/spiking-yolov3-tin
 y.cfg",it raise the error"raise NotImplementedError NotImplementedError"
 
File "/home/kugatsu/my_py_project/bindsnet/PyTorch-Spiking-YOLOv3-main/ann_to_snn.py", line 99, in 
 batch_size=8,
 File "/home/kugatsu/my_py_project/bindsnet/PyTorch-Spiking-YOLOv3-main/snn_test.py", line 40, in ann_evaluate
 output1, output2 = partial_ann(imgs)  # two branches
 File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
 result = self.forward(*input, **kwargs)
 File "/home/kugatsu/my_py_project/bindsnet/PyTorch-Spiking-YOLOv3-main/ann_to_snn.py", line 26, in forward
 x = self.listi
 File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
 result = self.forward(*input, **kwargs)
 File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
 input = module(input)
 File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
 result = self.forward(*input, **kwargs)
 File "/home/kugatsu/anaconda3/envs/Bindsnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 223, in _forward_unimplemented
 raise NotImplementedError
 NotImplementedError

**Comment by CHonChou** [comment]
i've already run the command"python3 train.py --model_def config/spiking-yolov3-tiny.cfg 
" and trained the model

**Comment by cwq159** [comment]
and your transforming command line is "python3 ann_to_snn.py --model_def config/spiking-yolov3-tiny.cfg --weights_path checkpoints/spiking-yolov3-tiny_ckpt_99.pth" ?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上7:50
收件人:&nbsp;"cwq159/PyTorch-Spiking-YOLOv3"<PyTorch-Spiking-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"Galaxy"<weiqian-chen@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] raise NotImplementedError NotImplementedError (#1)





 
i've already run the command"python3 train.py --model_def config/spiking-yolov3-tiny.cfg
 " and trained the model

**Comment by CHonChou** [comment]
the command line is"python3 ann_to_snn.py --model_def config/spiking-yolov3-tiny.cfg --weights_path weights/yolov3.weights"
and the weights/yolov3.weights is where the weights located

**Comment by cwq159** [comment]
sorry, u can't use yolov3.weights, because the whole yolov3 architecture hasn't been supported yet. u have to use the weights corresponding to the model config.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上8:00
收件人:&nbsp;"cwq159/PyTorch-Spiking-YOLOv3"<PyTorch-Spiking-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"Galaxy"<weiqian-chen@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] raise NotImplementedError NotImplementedError (#1)





 
the command line is"python3 ann_to_snn.py --model_def config/spiking-yolov3-tiny.cfg --weights_path weights/yolov3.weights"
 and the weights/yolov3.weights is where the weights located

**Comment by CHonChou** [comment]
Can you be more specific, for example, which weight file can I use for conversion

**Comment by cwq159** [comment]
plz go to /checkpoints, u can see &nbsp;"spiking-yolov3-tiny_ckpt_*.pth" 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上8:08
收件人:&nbsp;"cwq159/PyTorch-Spiking-YOLOv3"<PyTorch-Spiking-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"Galaxy"<weiqian-chen@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] raise NotImplementedError NotImplementedError (#1)





 
Can you be more specific, for example, which weight file can I use for conversion

**Comment by CHonChou** [comment]
only the“yolov3_ckpt_*.pth” in the /checkpoints file ,no "spiking-yolov3-tiny_ckpt_*.pth"

**Comment by cwq159** [comment]
in train.py, line 154, u can revise the checkpoint file name




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上9:34
收件人:&nbsp;"cwq159/PyTorch-Spiking-YOLOv3"<PyTorch-Spiking-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"Galaxy"<weiqian-chen@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] raise NotImplementedError NotImplementedError (#1)





 
only the“yolov3_ckpt_.pth” in the /checkpoints file ,no "spiking-yolov3-tiny_ckpt_.pth"

**Comment by CHonChou** [comment]
I have changed my command to “python3 ann_to_snn.py --model_def config/spiking-yolov3-tiny.cfg --weights_path checkpoints/yolov3_ckpt_99.pth”,
yolov3_ckpt_99.pth is the file name set by my train.py line 154, but This error still occurs. I have searched on google. Some people say that this is a problem with the forward function, but I still don’t know how to solve this problem.

**Comment by cwq159** [comment]
sorry, i've found the problem. it's because i've changed a new model called "spiking-yolov3-tiny-v2.cfg" and the corresponding forward function in ann-to-snn.py line 16 to 36. u can see the original version in my history committed on Sep 29, 2020.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上9:45
收件人:&nbsp;"cwq159/PyTorch-Spiking-YOLOv3"<PyTorch-Spiking-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"Galaxy"<weiqian-chen@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] raise NotImplementedError NotImplementedError (#1)





 
I have changed my command to “python3 ann_to_snn.py --model_def config/spiking-yolov3-tiny.cfg --weights_path checkpoints/yolov3_ckpt_99.pth”,
 yolov3_ckpt_99.pth is the file name set by my train.py line 154, but This error still occurs. I have searched on google. Some people say that this is a problem with the forward function, but I still don’t know how to solve this problem.

**Comment by CHonChou** [comment]
Thank you very much for your reply, I will try to fix this problem

**Comment by CHonChou** [comment]
I only need to change the 16th to 36th lines of ann_to_snn.py? Will directly changing these places not affect other parts?

**Comment by cwq159** [comment]
you're welcome~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上10:05
收件人:&nbsp;"cwq159/PyTorch-Spiking-YOLOv3"<PyTorch-Spiking-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"Galaxy"<weiqian-chen@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] raise NotImplementedError NotImplementedError (#1)





 
Thank you very much for your reply, I will try to fix this problem

**Comment by CHonChou** [comment]
I changed the 16th to 36th lines of ann_to_snn.py, but a new error occurred, the parameter shape does not match

**Comment by cwq159** [comment]
plz use the whole project committed on Sep 29, 2020




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上10:17
收件人:&nbsp;"cwq159/PyTorch-Spiking-YOLOv3"<PyTorch-Spiking-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"Galaxy"<weiqian-chen@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] raise NotImplementedError NotImplementedError (#1)





 
I changed the 16th to 36th lines of ann_to_snn.py, but a new error occurred, the parameter shape does not match

**Comment by CHonChou** [comment]
When I use your historical code on sep 29, the following error will be generated:
TypeError:'NoneType' object is not subscriptable

**Comment by CHonChou** [comment]
utils/augmentations.py", line 8, in horisontal_flip
    targets[:, 2] = 1 - targets[:, 2]
TypeError: 'NoneType' object is not subscriptable

**Comment by cwq159** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    There maybe some bugs in the history version. I’ll update a whole new version right now.
    
        
            
        
    
    
    
    

    

    

    On 11/17/2020 20:03，CHonChou<notifications@github.com> wrote： 



utils/augmentations.py", line 8, in horisontal_flip
targets[:, 2] = 1 - targets[:, 2]
TypeError: 'NoneType' object is not subscriptable

**Comment by CHonChou** [comment]
thanks a lot for that
