### ISSUE TITLE
Multi-gpu training

### ISSUE THREAD

**Issue by Yiiiike** [cwq159/PyTorch-Spiking-YOLOv3#18]
您好，我在训练的过程中遇到了显存不够的问题。
请问可以使用多块gpu运行ann-to-snn代码吗？如果可以的话，使用方法是什么呢？
谢谢您。

**Comment by Yiiiike** [comment]
非常抱歉，我已经找到了多gpu训练的方法。
打扰您了。

**Comment by Berumotto1** [comment]
请问怎么使用多gpu运行ann-to-snn的代码？
