### ISSUE TITLE
How did you encode the images?

### ISSUE THREAD

**Issue by hanebarla** [cwq159/PyTorch-Spiking-YOLOv3#47]
I read your code, but I can't find a code block that encode float image to sets of spikes.
If I missed it, sorry.

**Comment by cwq159** [comment]
In [SpikeTensor](https://github.com/cwq159/PyTorch-Spiking-YOLOv3/blob/ultralytics/spiking_utils/spike_tensor.py)

**Comment by hanebarla** [comment]
Thanks!
