### ISSUE TITLE
Changing batch_size causes error in snn_evaluate

### ISSUE THREAD

**Issue by rashmi-ar** [cwq159/PyTorch-Spiking-YOLOv3#49]
Hello author,

changing batch_size to default 1 for training and testing is causing error while transforming ann to snn (for yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg). The following error occurs in snn_evaluate,
  File "ann_to_snn.py", line 183, in <module>
    snn_results, maps, firing_ratios = snn_evaluate(opt,
  File "/PyTorch-Spiking-YOLOv3/spiking_utils/snn_evaluate.py", line 276, in snn_evaluate
    output_snn1, output_snn2 = snn(data)  # two branches
ValueError: too many values to unpack (expected 2)

Please let me know what may have gone wrong here.
Thanks in advance.

**Comment by hanbaobao950123** [comment]
maybe [#4](https://github.com/cwq159/PyTorch-Spiking-YOLOv3/issues/44) can help you.

**Comment by sahenderson10** [comment]
Hi Rashmi, did you get this code to work? How did you grab the dataset?

**Comment by rashmi-ar** [comment]
Hi @sahenderson10 ! You can check **data/get_coco_dataset.sh** file to download images and metadata or download the dataset from https://pjreddie.com/media/files/train2014.zip and https://pjreddie.com/media/files/val2014.zip

**Comment by sahenderson10** [comment]
Thank you! Once we have a dataset, how do we load it into train.py? It is not too clear to me. I have a custom dataset I would like to load in. I appreciate the help, I am not an expert at Python

**Comment by sahenderson10** [comment]
I have downloaded val2014 and train2014 and put them in the data file. How do I create the coco.data file to run the code?

**Comment by rashmi-ar** [comment]
Hi @sahenderson10 ! This may help - https://github.com/cwq159/PyTorch-Spiking-YOLOv3/issues/50#issuecomment-1279941778

**Comment by rashmi-ar** [comment]
Downgrading the python and pytorch version, python=3.7 and pytorch=1.3, solved the issue.
